AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Echo as Service with Security Group and
  EC2 Instance

Parameters:
  KeyPair:
    Description: Asks for the key pair created on EC2
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  StandardSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access on port 22 and 3000 via any IP address
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0  

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0df368112825f8d8f # eu-west-1, Ubuntu Server 24.04 LTS
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !Ref StandardSecurityGroup